# Generated by Django 4.1.1 on 2022-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_category_task_image_task_level_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='draw',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
