# Generated by Django 4.1 on 2022-09-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dcl',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
