# Generated by Django 4.1 on 2022-09-26 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0005_task_dcl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.CharField(max_length=30)),
                ('user_category', models.IntegerField(default=1)),
                ('user_level', models.IntegerField(default=0)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.IntegerField(default=0)),
                ('stage0_errors', models.IntegerField(default=0)),
                ('stage1_errors', models.IntegerField(default=0)),
                ('stage2_errors', models.IntegerField(default=0)),
                ('student_draw', models.JSONField(blank=True, null=True)),
                ('student_dcl', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.account')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
