# Generated by Django 4.1 on 2022-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_account_taskperstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskperstudent',
            name='stage0_errors',
        ),
        migrations.RemoveField(
            model_name='taskperstudent',
            name='stage1_errors',
        ),
        migrations.RemoveField(
            model_name='taskperstudent',
            name='stage2_errors',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskperstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
