# Generated by Django 4.1 on 2022-09-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_taskperstudent_stage0_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperstudent',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
